// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
insert into orders (customer_id) values ($1) returning id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
insert into order_items (product_id, quantity, price_in_cents, order_id) values ($1, $2, $3, $4) returning id, product_id, quantity, price_in_cents, order_id
`

type CreateOrderItemParams struct {
	ProductID    int64       `json:"product_id"`
	Quantity     pgtype.Int4 `json:"quantity"`
	PriceInCents int32       `json:"price_in_cents"`
	OrderID      int64       `json:"order_id"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
		arg.OrderID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
		&i.OrderID,
	)
	return i, err
}

const findProductById = `-- name: FindProductById :one
select id, name, price_in_cents, quantity, created_at from products where id = $1
`

func (q *Queries) FindProductById(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
select id, name, price_in_cents, quantity, created_at from products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
